### ISSUE TITLE
Include updated start.elf for custom raspberrypi

### ISSUE THREAD

**Issue by acostach** [balena-io-modules/etcher-sdk#221]
This updated start.elf file has been provided by upstream raspberrypi/usbboot and fixes flashing custom raspberrypis that use an eMMC: https://github.com/balena-io-modules/node-raspberrypi-usbboot/pull/41

Including this updated firmware will allow testbot, witch uses etcher-sdk, to provision this type of raspberrypis for automated testing.

**Comment by acostach** [comment]
Added in https://github.com/balena-io-modules/etcher-sdk/pull/227 which is waiting for review

**Comment by lurch** [comment]
> Added in #227 which...

...has been merged? :wink:

**Comment by acostach** [comment]
@lurch yes. Do you need this for an eMMC Pi?

**Comment by lurch** [comment]
Nope, I was just trying to help by pointing out a still-open issue, which looks like it was fixed by a merged PR.
